# =============================================================================
# Pathogen Detection Pipeline Configuration
# =============================================================================

# Working directory
workdir: "."

# Pipeline type - pathogen detection specific
pipeline_type: "pathogen_detection"
application: "diagnostic"  # diagnostic, surveillance, research

# Target pathogen groups
target_pathogens:
  bacteria:
    enabled: true
    priority_pathogens:
      - "Escherichia coli"
      - "Salmonella enterica"
      - "Staphylococcus aureus"
      - "Listeria monocytogenes"
      - "Campylobacter jejuni"
      - "Clostridium difficile"
      - "Mycobacterium tuberculosis"
    
  viruses:
    enabled: true
    priority_pathogens:
      - "SARS-CoV-2"
      - "Influenza A virus"
      - "Respiratory syncytial virus"
      - "Norovirus"
      - "Hepatitis B virus"
    
  fungi:
    enabled: false
    priority_pathogens:
      - "Candida albicans"
      - "Aspergillus fumigatus"
      - "Cryptococcus neoformans"
    
  parasites:
    enabled: false
    priority_pathogens:
      - "Plasmodium falciparum"
      - "Giardia lamblia"
      - "Cryptosporidium parvum"

# Design modes for pathogen detection
design_modes:
  - "species_specific"  # High specificity for single species
  - "genus_specific"    # Broader detection within genus
  - "multi_pathogen"    # Panel for multiple pathogens

# =============================================================================
# Reference Databases for Pathogen Detection
# =============================================================================

databases:
  # Primary pathogen reference genomes
  pathogens:
    bacteria:
      # NCBI RefSeq bacterial genomes
      refseq_bacteria: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/"
      # 16S rRNA sequences
      silva_16s: "https://www.arb-silva.de/fileadmin/silva_databases/release_138_1/Exports/SILVA_138.1_SSURef_tax_silva.fasta.gz"
      # RDP 16S database
      rdp_16s: "https://rdp.cme.msu.edu/misc/resources.jsp"
    
    viruses:
      # NCBI RefSeq viral genomes
      refseq_viruses: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/viral/"
      # ICTV virus metadata
      ictv_metadata: "https://talk.ictvonline.org/files/master-species-lists/"
    
    fungi:
      # UNITE fungal ITS database
      unite_its: "https://doi.plutof.ut.ee/doi/10.15156/BIO/1280049"
      # RefSeq fungal genomes
      refseq_fungi: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/fungi/"
  
  # Host genomes for exclusion
  hosts:
    human:
      genome: "https://ftp.ensembl.org/pub/release-111/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
      transcriptome: "https://ftp.ensembl.org/pub/release-111/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz"
    
    mouse:
      genome: "https://ftp.ensembl.org/pub/release-111/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz"
    
    livestock:
      bovine: "https://ftp.ensembl.org/pub/release-111/fasta/bos_taurus/dna/Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa.gz"
      porcine: "https://ftp.ensembl.org/pub/release-111/fasta/sus_scrofa/dna/Sus_scrofa.Sscrofa11.1.dna.primary_assembly.fa.gz"
  
  # Taxonomy database
  taxonomy:
    ncbi_taxonomy: "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"
    names_dmp: "names.dmp"
    nodes_dmp: "nodes.dmp"
  
  # Antimicrobial resistance genes
  amr:
    card_database: "https://card.mcmaster.ca/latest/data"
    resfinder: "https://cge.food.dtu.dk/services/ResFinder/"
    arg_annot: "https://www.mediterranee-infection.com/base/plasmids/arg_annot.html"
  
  # Virulence factors
  virulence:
    vfdb: "http://www.mgc.ac.cn/VFs/Down/VFDB_setB_nt.fas.gz"
    victors: "http://www.phidias.us/victors/downloads.php"

# =============================================================================
# Target Genes/Regions for Pathogen Detection
# =============================================================================

target_genes:
  bacteria:
    universal:
      - name: "16S_rRNA"
        regions: ["V1-V2", "V3-V4", "V4", "V6-V8"]
        primers_available: true
        resolution: "genus_species"
      - name: "23S_rRNA"
        regions: ["D1-D3", "full_length"]
        primers_available: false
        resolution: "species_strain"
    
    species_specific:
      - name: "rpoB"
        description: "RNA polymerase beta subunit"
        resolution: "species"
        organisms: ["Mycobacterium", "Enterococcus"]
      - name: "gyrB"
        description: "DNA gyrase B subunit"
        resolution: "species_strain"
        organisms: ["Escherichia", "Salmonella"]
      - name: "tuf"
        description: "Elongation factor Tu"
        resolution: "species"
        organisms: ["Enterococcus", "Staphylococcus"]
  
  viruses:
    universal:
      - name: "pol"
        description: "Polymerase gene"
        resolution: "species"
      - name: "capsid"
        description: "Capsid protein genes"
        resolution: "strain"
    
    specific:
      - name: "RdRp"
        description: "RNA-dependent RNA polymerase"
        organisms: ["SARS-CoV-2", "Influenza"]
      - name: "N_gene"
        description: "Nucleocapsid gene"
        organisms: ["SARS-CoV-2"]

# =============================================================================
# Pathogen-Specific Design Parameters
# =============================================================================

primer3:
  species_specific:
    primer_opt_size: 22
    primer_min_size: 18
    primer_max_size: 28
    primer_opt_tm: 60.0
    primer_min_tm: 58.0
    primer_max_tm: 62.0
    primer_min_gc: 40.0
    primer_max_gc: 65.0
    product_size_range: "80-200"
    primer_max_poly_x: 3
    primer_max_ns_accepted: 0
  
  genus_specific:
    primer_opt_size: 20
    primer_min_size: 18
    primer_max_size: 25
    primer_opt_tm: 60.0
    primer_min_tm: 57.0
    primer_max_tm: 63.0
    primer_min_gc: 35.0
    primer_max_gc: 70.0
    product_size_range: "100-300"
    primer_max_poly_x: 4
    primer_max_ns_accepted: 1
  
  multi_pathogen:
    primer_opt_size: 25
    primer_min_size: 20
    primer_max_size: 30
    primer_opt_tm: 62.0
    primer_min_tm: 60.0
    primer_max_tm: 65.0
    primer_min_gc: 40.0
    primer_max_gc: 60.0
    product_size_range: "120-250"
    primer_max_poly_x: 3
    primer_max_ns_accepted: 0

# =============================================================================
# Pathogen Detection Screening Parameters
# =============================================================================

screening:
  # Primary pathogen specificity
  pathogen_specificity:
    min_identity: 95.0  # Minimum identity to target pathogen
    max_cross_reactivity: 85.0  # Maximum allowed cross-reactivity
    phylogenetic_distance_threshold: 3  # Taxonomic levels
  
  # Host exclusion (critical for clinical applications)
  host_exclusion:
    max_host_similarity: 75.0  # Maximum similarity to host sequences
    critical_hosts: ["human", "mouse"]  # Must screen against these
    exclusion_databases: ["genome", "transcriptome", "microbiome"]
  
  # Cross-pathogen screening
  cross_pathogen:
    check_related_species: true
    family_level_screening: true
    max_acceptable_cross_reactivity: 80.0
  
  # Environmental/contaminant screening
  contaminant_screening:
    check_lab_contaminants: true
    check_reagent_contamination: true
    common_contaminants:
      - "Escherichia coli DH5alpha"  # Lab strain
      - "Pseudomonas fluorescens"     # Environmental
      - "Bacillus subtilis"           # Common contaminant

# =============================================================================
# Clinical and Regulatory Requirements
# =============================================================================

clinical:
  # Performance specifications
  performance_targets:
    analytical_sensitivity: "10 CFU/ml"  # or copies/μl
    analytical_specificity: ">99%"
    clinical_sensitivity: ">95%"
    clinical_specificity: ">98%"
    limit_of_detection: "95% at target concentration"
  
  # Validation requirements
  validation:
    min_validation_samples: 100
    include_negative_controls: true
    include_interfering_substances: true
    stability_testing_required: true
    reproducibility_studies: true
  
  # Quality control
  quality_control:
    positive_controls: true
    negative_controls: true
    internal_controls: true  # extraction/amplification controls
    contamination_monitoring: true

# =============================================================================
# Multi-pathogen Panel Design
# =============================================================================

panels:
  respiratory_panel:
    pathogens:
      - "SARS-CoV-2"
      - "Influenza A"
      - "Influenza B"  
      - "RSV"
      - "Mycoplasma pneumoniae"
      - "Chlamydia pneumoniae"
    multiplex_compatibility: true
    max_amplicon_size: 200
    tm_uniformity: 2.0  # °C
  
  foodborne_panel:
    pathogens:
      - "Salmonella spp."
      - "Listeria monocytogenes"
      - "Escherichia coli O157:H7"
      - "Campylobacter jejuni"
      - "Staphylococcus aureus"
    sample_types: ["food", "environmental"]
    enrichment_required: true
  
  antimicrobial_resistance:
    targets:
      - "mecA"          # MRSA
      - "vanA/vanB"     # VRE
      - "blaCTX-M"      # ESBL
      - "blaKPC"        # Carbapenemase
      - "mcr-1"         # Colistin resistance
    clinical_breakpoints: true

# =============================================================================
# Database Configuration (Extended for Pathogen Detection)
# =============================================================================

database:
  # Connection settings
  host: "localhost"
  port: 5432
  database: "pathogen_oligodb"
  user: "postgres"
  password: ""
  
  # Pathogen-specific settings
  taxonomy_integration: true
  host_exclusion_tracking: true
  amr_integration: true
  virulence_tracking: true
  
  # Clinical data tracking
  clinical_validation_tracking: true
  regulatory_compliance: true
  audit_trail: true
  
  # Performance optimization for pathogen data
  pathogen_indexes: true
  taxonomy_indexes: true
  similarity_search_optimization: true

# =============================================================================
# Output and Reporting
# =============================================================================

output:
  # Standard formats
  formats:
    - "tsv"
    - "fasta"
    - "json"
    - "xml"  # For regulatory submissions
  
  # Pathogen-specific outputs
  pathogen_specific:
    taxonomic_classification: true
    cross_reactivity_matrix: true
    host_exclusion_report: true
    clinical_performance_summary: true
    regulatory_documentation: true
  
  # Quality metrics
  quality_metrics:
    analytical_performance: true
    cross_reactivity_analysis: true
    phylogenetic_analysis: true
    contamination_assessment: true

# =============================================================================
# Tool Configuration
# =============================================================================

tools:
  # Sequence analysis
  blast:
    pathogen_databases: true
    taxonomy_aware: true
    low_complexity_filter: false  # Important for pathogen detection
  
  # Phylogenetic analysis
  phylogeny:
    tree_construction: "neighbor_joining"
    distance_metric: "kimura_2_parameter"
    bootstrap_replicates: 1000
  
  # Multiplex design
  multiplex:
    primer_dimer_check: true
    amplicon_size_balancing: true
    tm_balancing: true
    cross_reactivity_minimization: true

# =============================================================================
# Validation and Testing
# =============================================================================

validation:
  # Test organisms (reference strains)
  reference_strains:
    positive_controls:
      - strain: "E. coli ATCC 25922"
        expected_result: "positive"
        target_genes: ["16S", "gyrB"]
      - strain: "S. aureus ATCC 29213"
        expected_result: "positive"
        target_genes: ["16S", "tuf"]
    
    negative_controls:
      - organism: "Human DNA"
        expected_result: "negative"
        concentration: "100 ng/μl"
      - organism: "No template control"
        expected_result: "negative"
  
  # Cross-reactivity testing
  cross_reactivity_panel:
    - "Enterococcus faecalis"
    - "Streptococcus pyogenes"
    - "Pseudomonas aeruginosa"
    - "Candida albicans"
  
  # Analytical sensitivity
  sensitivity_testing:
    dilution_series: [1e6, 1e5, 1e4, 1e3, 1e2, 1e1]
    replicates_per_dilution: 20
    acceptance_criteria: "95% detection at target LOD"

# =============================================================================
# Regulatory and Compliance
# =============================================================================

regulatory:
  intended_use: "research_use_only"  # or "in_vitro_diagnostic"
  
  # FDA requirements (if applicable)
  fda:
    class: "II"  # Medical device class
    predicate_device: ""
    clinical_studies_required: false
  
  # CE marking (if applicable)
  ce_ivd:
    notified_body: ""
    performance_evaluation: true
    post_market_surveillance: true
  
  # Quality management
  quality_system:
    iso_13485: false
    iso_15189: false  # Medical laboratories
    clia_compliance: false  # US clinical labs

# =============================================================================
# Environment Modules (Pathogen-specific tools)
# =============================================================================

modules:
  # Standard tools
  blast: "blast/2.12.0"
  bowtie2: "bowtie2/2.4.5"
  bcftools: "bcftools/1.17"
  samtools: "samtools/1.17"
  primer3: "primer3/2.6.1"
  
  # Pathogen-specific tools
  kraken2: "kraken2/2.1.2"        # Taxonomic classification
  bracken: "bracken/2.7"          # Species abundance estimation
  metaphlan: "metaphlan/4.0"      # Microbial profiling
  centrifuge: "centrifuge/1.0.4"  # Metagenomic classifier
  
  # Phylogenetic analysis
  muscle: "muscle/5.1"            # Multiple sequence alignment
  iqtree: "iqtree/2.2.0"         # Phylogenetic tree construction
  fasttree: "fasttree/2.1.11"    # Fast phylogenetic trees
  
  # AMR analysis
  abricate: "abricate/1.0.1"     # AMR gene screening
  rgi: "rgi/6.0.2"               # CARD resistance gene identifier
  
  # Virulence analysis
  virulencefinder: "virulencefinder/2.0"

# =============================================================================
# Resource Allocation (Adjusted for Pathogen Databases)
# =============================================================================

resources:
  # Higher memory requirements for pathogen databases
  memory:
    taxonomy_processing: "16G"
    pathogen_indexing: "32G"
    cross_reactivity_screening: "24G"
    phylogenetic_analysis: "8G"
  
  # Thread allocation
  threads:
    taxonomy_processing: 4
    pathogen_indexing: 8
    cross_reactivity_screening: 12
    multiplex_optimization: 6

# =============================================================================
# Quality Control Thresholds (Pathogen-specific)
# =============================================================================

qc:
  # Stricter requirements for pathogen detection
  specificity_thresholds:
    species_level: 0.95
    genus_level: 0.90
    family_level: 0.85
  
  # Cross-reactivity limits
  cross_reactivity:
    max_off_targets: 3
    max_host_similarity: 0.75
    max_related_pathogen_similarity: 0.85
  
  # Clinical performance requirements
  clinical_performance:
    min_sensitivity: 0.95
    min_specificity: 0.98
    max_false_positive_rate: 0.02
    max_false_negative_rate: 0.05

